# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, Windows ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup JFrog CLI 2
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_URL: https://localhost:8082
          JF_ACCESS_TOKEN: ${{ secrets.JF_SVC_TOKEN }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd src/com/bilibili/unsafe
          run-ant.bat -f new_build.xml build
        shell: cmd
        
      - name: Upload files to JFrog
        run: |
         jf --version
         jf rt u "Tools\*.*" quantstudio5dx-desktop/bin/ --ant --flat --quiet
